### ISSUE TITLE
Scylla startup stuck after terminate k8s host & decomission node when adding node back

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1689]
### What happened?

In disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node nemesis we terminate k8s host and decommision scylla node. After that new node is added. Upon this step, in logs I can see new node is starting but stuck at some point indefinitely and failing the test. From logs we can see:
```
INFO  2023-12-31 04:40:20,903 [shard  0] compaction - [Compact system_schema.tables b46cdb70-a796-11ee-96e1-17c6dfed627b] Compacting [/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-42-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-56-big-Data.db:level=0:origin=compaction]
INFO  2023-12-31 04:40:20,908 [shard  0] compaction - [Compact system_schema.tables b46cdb70-a796-11ee-96e1-17c6dfed627b] Compacted 2 sstables to [/var/lib/scylla/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-70-big-Data.db:level=0]. 39kB to 22kB (~56% of original) in 4ms = 9MB/s. ~256 total partitions merged to 8.
You current Scylla release is 2023.1.2 while the latest patch release is 2023.1.3, update for the latest bug fixes and improvements

E1231 04:40:25.717355       1 sidecar/probes.go:101] "readyz probe: can't get scylla native transport" err="agent [HTTP 404] Not found" Service="scylla/sct-cluster-eu-north-1-rack-1-2" Node="10.0.8.60"
E1231 04:40:35.714305       1 sidecar/probes.go:101] "readyz probe: can't get scylla native transport" err="agent [HTTP 404] Not found" Service="scylla/sct-cluster-eu-north-1-rack-1-2" Node="10.0.8.60"
I1231 04:40:44.553084       1 sidecar/sync.go:172] "Successfully updated service annotations" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
E1231 04:40:45.713654       1 sidecar/probes.go:101] "readyz probe: can't get scylla native transport" err="agent [HTTP 404] Not found" Service="scylla/sct-cluster-eu-north-1-rack-1-2" Node="10.0.8.60"
[...]
```

### What did you expect to happen?

node started up properly and returned to cluster

### How can we reproduce it (as minimally and precisely as possible)?

run SCT test:https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-multidc-12h-eks

### Scylla Operator version

v1.12.0-alpha.1-49-g4cc81a6

## Installation details

Kernel Version: 5.10.199-190.747.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.2-20231001.646df23cc4b3` with build-id `367fcf1672d44f5cbddc88f946cf272e2551b85a`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-144-g60f7824
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-multidc-12h-eks`
Test id: `304bf0b2-64f7-4266-96c6-4f58e2622706`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-multidc-12h-eks`
Test config file(s):

- [longevity-scylla-operator-multidc-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/53cd2d2662565307007e2de2ce4765a9bf30c831/test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 304bf0b2-64f7-4266-96c6-4f58e2622706`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=304bf0b2-64f7-4266-96c6-4f58e2622706)
- Show all stored logs command: `$ hydra investigate show-logs 304bf0b2-64f7-4266-96c6-4f58e2622706`

## Logs:
- **kubernetes-304bf0b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/kubernetes-304bf0b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/kubernetes-304bf0b2.tar.gz)
- **kubernetes-must-gather-304bf0b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/kubernetes-must-gather-304bf0b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/kubernetes-must-gather-304bf0b2.tar.gz)
- **db-cluster-304bf0b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/db-cluster-304bf0b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/db-cluster-304bf0b2.tar.gz)
- **sct-runner-events-304bf0b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/sct-runner-events-304bf0b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/sct-runner-events-304bf0b2.tar.gz)
- **sct-304bf0b2.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/sct-304bf0b2.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/sct-304bf0b2.log.tar.gz)
- **loader-set-304bf0b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/loader-set-304bf0b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/loader-set-304bf0b2.tar.gz)
- **monitor-set-304bf0b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/monitor-set-304bf0b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/304bf0b2-64f7-4266-96c6-4f58e2622706/20231231_054908/monitor-set-304bf0b2.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-multidc-12h-eks/7/)
[Argus](https://argus.scylladb.com/test/9c2d421e-4c47-4481-88c9-f0463e6a6c01/runs?additionalRuns[]=304bf0b2-64f7-4266-96c6-4f58e2622706)
</details>

                            

### Please attach the must-gather archive.

see in logs section in argus: https://argus.scylladb.com/test/9c2d421e-4c47-4481-88c9-f0463e6a6c01/runs?additionalRuns[]=304bf0b2-64f7-4266-96c6-4f58e2622706

**Comment by vponomaryov** [comment]
> > see in logs section in argus: [https://argus.scylladb.com/test/9c2d421e-4c47-4481-88c9-f0463e6a6c01/runs?additionalRuns[]=304bf0b2-64f7-4266-96c6-4f58e2622706](https://argus.scylladb.com/test/9c2d421e-4c47-4481-88c9-f0463e6a6c01/runs?additionalRuns%5B%5D=304bf0b2-64f7-4266-96c6-4f58e2622706)
> 
> please upload the must-gather archive here so it's not hidden behind argus login

The permissions thing during the login was fixed several weeks ago.

**Comment by tnozicka** [comment]
> The permissions thing during the login was fixed several weeks ago.

nope, that's still an issue  (but that's not a discussion to have here)

> It is already in the bugreport, just open the Logs and commands drop-down.

someone could expect `must-gather` archive to be uploaded in the section that's called "Must Gather" instead behind a drop down in different section but ok

please follow the bug report template next time

**Comment by vponomaryov** [comment]
Note that it was run using not latest `latest` helm chart (https://github.com/scylladb/scylla-operator/issues/1690) but with `latest` operator docker image for the moment of running this job.

**Comment by fruch** [comment]
happened in more simple use-case (without multi-dc)

seem like after decommission of `sct-cluster-eu-north-1-rack-1-2`, it not finding it in some mapping, and that it's 
we do get this pod recreate as it should:
```
0128 02:13:00.518214       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
I0128 02:13:01.961396       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
I0128 02:13:02.198770       1 sidecar/sync.go:93] "The node is already decommissioned"
E0128 02:13:02.212296       1 sidecar/controller.go:143] syncing key 'scylla/sct-cluster-eu-north-1-rack-1-2' failed: can't sync the HostID annotation: local host ID "e7a2caa3-f5cf-43ca-b5e5-44ccbb09bbbd" not found in IP to hostID mapping: map[172.20.143.92:91a88b7e-7ab1-41a5-99a8-65c655f91620 172.20.171.182:c9b5114e-afa7-4070-8faa-257c8c0056b8]
E0128 02:13:02.214436       1 sidecar/controller.go:143] syncing key 'scylla/sct-cluster-eu-north-1-rack-1-2' failed: can't sync the HostID annotation: local host ID "e7a2caa3-f5cf-43ca-b5e5-44ccbb09bbbd" not found in IP to hostID mapping: map[172.20.143.92:91a88b7e-7ab1-41a5-99a8-65c655f91620 172.20.171.182:c9b5114e-afa7-4070-8faa-257c8c0056b8]
I0128 02:13:10.517568       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
I0128 02:13:20.517515       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
E0128 02:13:27.061272       1 sidecar/controller.go:143] syncing key 'scylla/sct-cluster-eu-north-1-rack-1-2' failed: can't sync the HostID annotation: local host ID "e7a2caa3-f5cf-43ca-b5e5-44ccbb09bbbd" not found in IP to hostID mapping: map[172.20.143.92:91a88b7e-7ab1-41a5-99a8-65c655f91620 172.20.171.182:c9b5114e-afa7-4070-8faa-257c8c0056b8]
I0128 02:13:30.517621       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
I0128 02:13:40.516908       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
I0128 02:13:50.517835       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
E0128 02:13:57.061494       1 sidecar/controller.go:143] syncing key 'scylla/sct-cluster-eu-north-1-rack-1-2' failed: can't sync the HostID annotation: local host ID "e7a2caa3-f5cf-43ca-b5e5-44ccbb09bbbd" not found in IP to hostID mapping: map[172.20.143.92:91a88b7e-7ab1-41a5-99a8-65c655f91620 172.20.171.182:c9b5114e-afa7-4070-8faa-257c8c0056b8]
I0128 02:14:00.517761       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
I0128 02:14:10.517329       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
I0128 02:14:16.961343       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
I0128 02:14:20.517667       1 sidecar/probes.go:113] "readyz probe: node is not ready" Service="scylla/sct-cluster-eu-north-1-rack-1-2"
```

## Installation details

Kernel Version: 5.10.205-195.804.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.3-20231219.b890271f125b` with build-id `26667e5fe9023e6f688ca3bab2ee5f910abfd2cb`


Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.1-86-g2e8beeb-latest
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-3h-eks`
Test id: `7d577809-ea14-45d0-82e3-e4c484c2a4e7`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-eks`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/cf79ff757eb5b3431035e688ede85c4ea1dae417/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 7d577809-ea14-45d0-82e3-e4c484c2a4e7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7d577809-ea14-45d0-82e3-e4c484c2a4e7)
- Show all stored logs command: `$ hydra investigate show-logs 7d577809-ea14-45d0-82e3-e4c484c2a4e7`


## Logs:
- **kubernetes-7d577809.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/kubernetes-7d577809.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/kubernetes-7d577809.tar.gz)
- **kubernetes-must-gather-7d577809.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/kubernetes-must-gather-7d577809.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/kubernetes-must-gather-7d577809.tar.gz)
- **db-cluster-7d577809.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/db-cluster-7d577809.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/db-cluster-7d577809.tar.gz)
- **sct-runner-events-7d577809.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/sct-runner-events-7d577809.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/sct-runner-events-7d577809.tar.gz)
- **sct-7d577809.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/sct-7d577809.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/sct-7d577809.log.tar.gz)
- **loader-set-7d577809.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/loader-set-7d577809.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/loader-set-7d577809.tar.gz)
- **monitor-set-7d577809.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/monitor-set-7d577809.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/monitor-set-7d577809.tar.gz)
- **parallel-timelines-report-7d577809.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/parallel-timelines-report-7d577809.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7d577809-ea14-45d0-82e3-e4c484c2a4e7/20240128_030149/parallel-timelines-report-7d577809.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/157/)
[Argus](https://argus.scylladb.com/test/028aa2df-5ce5-4883-a4a8-16bfbbe8dcc8/runs?additionalRuns[]=7d577809-ea14-45d0-82e3-e4c484c2a4e7)
</details>
