### ISSUE TITLE
longevity-scylla-operator-3h-gke-terminate-replace: drived scylla to have broken command line

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#730]
TestId: `801e256a-2bca-4c72-be78-40711c7838c9`
Job:
`https://jenkins.scylladb.com/view/scylla-operator/job/scylla-operator/job/operator-1.4/job/gke/job/longevity-scylla-operator-3h-gke-terminate-replace/3`

After running nemesis pod `sct-cluster-us-east1-b-us-east1-2` failed to not recover

Logs showed the following:
```
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-7 --smp 7 --overprovisioned --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=10.83.242.82 --broadcast-address 10.83.240.56 --broadcast-rpc-address 10.83.240.56 --replace-address-first-boot --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, io-properties-file: /etc/scylla.d/io_properties.yaml, cpuset: 0-7, smp: 7, overprovisioned, listen-address: 0.0.0.0, rpc-address: 0.0.0.0, seed-provider-parameters: seeds=10.83.242.82, broadcast-address: 10.83.240.56, broadcast-rpc-address: 10.83.240.56, replace-address-first-boot: --blocked-reactor-notify-ms, (positional) 999999999]
error: too many positional options have been specified on the command line
```

As you can see `--replace-address-first-boot` had no value: `--replace-address-first-boot --blocked-reactor-notify-ms 999999999`

Probably we need to guard to agains empty value on sidecar side
https://github.com/scylladb/scylla-operator/blob/be0e67fb21da920f07e4107334bf71af7e367940/pkg/sidecar/config/config.go#L230-L232

**To Reproduce**
1. Deploy scylla-operator on gke
2. Pick scylla pod to attack
3. Find node where pod is hosted
4. Drain k8s node: `kubectl drain node <node>` 
5. Uncordon k8s node: `kubectl uncordon node <node>` 
6. Wait till pod get scheduled again
7. Mark pod to be replaced: `kubectl label svc <svc> scylla/replace=""'`
8. Wait till pod is recreated and get to up and running state
 
**Expected behavior**
Pod is successfully recovered

**Logs**
db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/801e256a-2bca-4c72-be78-40711c7838c9/20210724_185703/db-cluster-801e256a.tar.gz
monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/801e256a-2bca-4c72-be78-40711c7838c9/20210724_185703/monitor-set-801e256a.tar.gz
loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/801e256a-2bca-4c72-be78-40711c7838c9/20210724_185703/loader-set-801e256a.tar.gz
sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/801e256a-2bca-4c72-be78-40711c7838c9/20210724_185703/sct-runner-801e256a.tar.gz
kubernetes  | https://cloudius-jenkins-test.s3.amazonaws.com/801e256a-2bca-4c72-be78-40711c7838c9/20210724_185703/kubernetes-801e256a.tar.gz 

**Environment:**
 - Platform: GKE
 - Kubernetes version: 
 - Scylla version: 4.4.2
 - Scylla-operator version: v1.4.0-beta.0-0-gf382529

**Comment by tnozicka** [comment]
This looks like a bug in Kubernetes. We have a PDB with `maxUnavailable: 1`, 3 pods, 2 of them are ready - when we try to evict the 3rd pod (unready) the API call fails with `Cannot evict pod as it would violate the pod's disruption budget.`, yet that isn't true because PDB accounts only for ready pods and we are deleting the one that isn't ready.

I guess we'll have to temporarily use delete and fix kube in the meantime.

**Comment by tnozicka** [comment]
btw. this should be fixed in kubernetes >= 1.20

**Comment by fruch** [comment]
@tnozicka @zimnx, I'm using kubernetes==1.21.1, and still see this error during the kind based functional tests:
```
< t:2022-07-12 10:51:35,560 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > cylla version 4.6.3-0.20220414.8bf149fdd with build-id 8d16d8972498cc769071ff25309b009eb77bf77a starting ...
< t:2022-07-12 10:51:35,561 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --smp 1 --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=10.96.115.97 --broadcast-address 10.96.241.247 --broadcast-rpc-address 10.96.241.247 --alternator-address 0.0.0.0 --replace-address-first-boot --blocked-reactor-notify-ms 999999999 --abort-on-lsa-bad-alloc=1 --enable-sstable-key-validation=1 --io-properties-file=/etc/scylla.d/io_properties.yaml --prometheus-address=0.0.0.0 --abort-on-internal-error=1 --abort-on-ebadf=1"
< t:2022-07-12 10:51:35,561 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, smp, (positional) 1, listen-address: 0.0.0.0, rpc-address: 0.0.0.0, seed-provider-parameters: seeds=10.96.115.97, broadcast-address: 10.96.241.247, broadcast-rpc-address: 10.96.241.247, alternator-address: 0.0.0.0, replace-address-first-boot: --blocked-reactor-notify-ms, (positional) 999999999, abort-on-lsa-bad-alloc: 1, enable-sstable-key-validation: 1, io-properties-file: /etc/scylla.d/io_properties.yaml, prometheus-address: 0.0.0.0, abort-on-internal-error: 1, abort-on-ebadf: 1]
< t:2022-07-12 10:51:35,561 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > error: too many positional options have been specified on the command line
```

### Logs
* db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/c37ee260-cc78-4dd8-9a5a-2b71f63e4a9e/20220712_114902/db-cluster-c37ee260.tar.gz
* sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/c37ee260-cc78-4dd8-9a5a-2b71f63e4a9e/20220712_114902/sct-runner-c37ee260.tar.gz
* kubernetes - https://cloudius-jenkins-test.s3.amazonaws.com/c37ee260-cc78-4dd8-9a5a-2b71f63e4a9e/20220712_114902/kubernetes-c37ee260.tar.gz
